export const GET_POST = "GET_POST"
export const GET_POST_OK = "GET_POST_OK"
export const GET_POST_FAIL = "GET_POST_FAIL"

export const GET_SINGLE_POST = "GET_SINGLE_POST"
export const GET_SINGLE_POST_OK = "GET_SINGLE_POST_OK"
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL"

